//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Commands
{
    using System;
    using System.ComponentModel.Design;
    using Microsoft.VisualStudio.Shell;
    
    internal partial class GuidSymbols
    {
        public const string PackageString = "8CA8D2A2-183B-4E91-BAA4-DAC042395F00";
        public const string PackageMenusString = "03B0E9DA-6932-4A4D-8319-9EB154D0A223";
        public const string PackageGroupsString = "7CC0649F-425A-4973-9BB2-4F40A7BE4B22";
        public const string PackageCommandsString = "BED49801-D15C-469D-9501-EE82C6B590D6";
        public static Guid Package = new Guid(PackageString);
        public static Guid PackageMenus = new Guid(PackageMenusString);
        public static Guid PackageGroups = new Guid(PackageGroupsString);
        public static Guid PackageCommands = new Guid(PackageCommandsString);
    }
    /// <summary>
    /// Represents the <see cref="IDSymbols"/> class.
    /// </summary>
    internal partial class IDSymbols
    {
        public const int IDM_RESTART = 257;
        public const int IDG_RESTART = 17;
        public const int IDG_RESTART_CMDS = 18;
        public const int RestartCommand = 1;
        public const int RestartElevatedCommand = 2;
    }
    /// <summary>
    /// Represents the <see cref="Commands"/> class.
    /// </summary>
    internal partial class Commands
    {
        public static CommandID RestartCommandCommandId = new CommandID(GuidSymbols.PackageCommands, IDSymbols.RestartCommand);
        public static CommandID RestartElevatedCommandCommandId = new CommandID(GuidSymbols.PackageCommands, IDSymbols.RestartElevatedCommand);
    }
    /// <summary>
    ///  Serves as the abstract base for classes that handle commands.
    /// </summary>
    internal abstract partial class AbstractCommandHandler
    {
        /// <summary>
        ///  Initializes a new instance of the <see cref="AbstractCommandHandler"/> class.
        /// </summary>
        protected AbstractCommandHandler()
        {
        }
        /// <summary>
        /// When overridden in a derived class, handles the RestartCommand command.
        /// </summary>
        /// <param name="sender">The <see cref="object"/> initiating the command.</param>
        /// <param name="e">The <see cref="EventArgs"/> that will ultimately handle the command.</param>
        public virtual void OnExecuteRestartCommand(object sender, EventArgs e)
        {
        }
        /// <summary>
        /// When overridden in a derived class, handles the RestartElevatedCommand command.
        /// </summary>
        /// <param name="sender">The <see cref="object"/> initiating the command.</param>
        /// <param name="e">The <see cref="EventArgs"/> that will ultimately handle the command.</param>
        public virtual void OnExecuteRestartElevatedCommand(object sender, EventArgs e)
        {
        }
    }
    /// <summary>
    ///  Entry point for handling commands.
    /// </summary>
    internal partial class CommandHandler : AbstractCommandHandler
    {
    }
    /// <summary>
    ///  Does the job no one else will do, and registers the commands.
    /// </summary>
    internal partial class CommandRegistrar
    {
        /// <summary>
        /// Registers the commands.
        /// </summary>
        /// <param name="service">the <see cref="OleMenuCommandService"/> that services the commands</param>
        /// <param name="handler">the <see cref="CommandHandler"/> class containing all of the handlers to the commands</param>
        public static void RegisterCommands(OleMenuCommandService service, CommandHandler handler)
        {
            RegisterCommand(service, Commands.RestartCommandCommandId, handler.OnExecuteRestartCommand);
            RegisterCommand(service, Commands.RestartElevatedCommandCommandId, handler.OnExecuteRestartElevatedCommand);
            Logger.Log("Registering command RestartCommand...");
            Logger.Log("Registering command RestartElevatedCommand...");
        }
        /// <summary>
        /// Registers a command.
        /// </summary>
        /// <param name="service">the OleCommandService that services the commands</param>
        /// <param name="cmdId">the CommandID that identifies the command</param>
        /// <param name="commandHanlder">the EventHandler responsible for handling the command</param>
        private static void RegisterCommand(OleMenuCommandService service, CommandID cmdId, EventHandler commandHandler)
        {
            OleMenuCommand command = new OleMenuCommand(commandHandler, cmdId);
            service.AddCommand(command);
        }
    }
}

